stages:
  prepare:
    cmd: python3.11 src/prepare.py data/raw data/prepared
    deps:
    - data/raw
    - src/prepare.py
    - src/utils/seed.py
    params:
    - prepare
    outs:
    - data/prepared
